name: Setup Audit
on:
  workflow_dispatch:
    inputs:
      audit_list_file:
        description: 'File name to create'
        required: true
        default: 'audit_list.txt'
      active_days:
        description: 'Number of days to check for repository activity'
        required: true
        default: 365
      start_date:
        description: 'Start date for the audit in YYYY-MM-DD format'
        required: true
      end_date:
        description: 'End date for the audit in YYYY-MM-DD format'
        required: true
      quarter:
        description: 'Quarter when audit was created [Q1, Q2, Q3, Q4]'
        required: true
        type: choice
        options:
          - Q1
          - Q2
          - Q3
          - Q4
      dry_run_enabled:
        description: 'Enable dry run mode'
        required: false
        default: 'false'

defaults:
  shell: bash

permissions:
  contents: write
  id-token: write
  issues: write

jobs:
  setup_audit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup gh CLI
        env:
          GH_CLI_TOKEN: ${{ secrets.GH_CLI_TOKEN }}
        run: |
          gh auth login --with-token <<< "${GH_CLI_TOKEN}"

      - name: Run audit prep
        run: |
          # Add your audit script or command here
          AUDIT_ARGS=-a ${{ inputs.active_days }} -s ${{ inputs.start_date }}" -e ${{ inputs.end_date }}" -q ${{ inputs.quarter }}" -r ${{ inputs.active_days }}"
          if [[ "${{ inputs.dry_run_enabled }}" = "true" ]]; then
            AUDIT_ARGS="${AUDIT_ARGS} -d"
          fi
          ./run_audit_prep.sh ${AUDIT_ARGS}
